server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    druid:
      first:
        url: jdbc:oracle:thin:@10.126.2.200:1521:xjsbfjk
        username: J1K_SBFYY
        password: oracle123
      second:
        url: jdbc:oracle:thin:@10.126.2.200:1521:xjsbfjk
        username: J1K_SBFFX_XJ
        password: oracle123
    ##关闭Favicon
  mvc:
    favicon:
      enabled: false
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间
    timeout: 5000
#配置PageHelper相关属性
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
 level:
  com.ywl.study.springsecurity.mapper: debug
# file: classpath:logback-spring.xml  如果不是classpath:logback-spring.xml 需要指定


